### ISSUE TITLE
Fetch not working properly with the registry

### ISSUE THREAD

**Issue by clauxx** [jolocom/jolocom-sdk#16]
### Describe the bug

The fetch implementation was [changed](https://github.com/jolocom/jolocom-sdk/commit/6c76996bef7d6fc0f518010c7fe254337657f420) from `RNFetchBlob` to `node-fetch`, which breaks on react-native projects. 

### To Reproduce

1. include SDK into react-native project
2. create an identity
3. fail with `RegistryCommitFailed` 

### Expected behavior

Successfully create an identity and commit it to the registry.

**Comment by mnzaki** [comment]
SDK defaults to node, we are extracting the react native stuff into a separate package hopefully some time soon!

Note that there are changes in #29 that might also result in similar issues unfortunately
