### ISSUE TITLE
SDK Documentation - Transports

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-sdk#74]
### Scope of the feature

As part of the guides related to `Installing / Configuring` the Jolocom-SDK, we should include a section on how to configure the supported / used transports.

### Tasks

Document the configuration of the various transports
- [ ] Using / supporting HTTP(s) as a client / server
- [ ] Using / supporting  WS(s) as a client / server.

**Comment by mnzaki** [comment]
Some initial work for this is at #75
